"""change latitude precision

Revision ID: 432abe0011be
Revises: c5249695002a
Create Date: 2022-11-23 10:57:39.353892

"""
import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision = '432abe0011be'
down_revision = 'c5249695002a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###