"""change latitude precision

Revision ID: c5249695002a
Revises: 
Create Date: 2022-11-23 10:43:01.705416

"""
import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision = 'c5249695002a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###